apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-back
  template:
    metadata:
      labels:
        app: my-back
    spec:
      containers:
      - name: my-back
        image: susguzman/so1-s223-back:0.1.1
        env:
        - name: ORACLE_USER
          value: oracle
        - name: ORACLE_PASS
          value: your_pass
        - name: ORACLE_CONNSTR
          value: localhost:1521/xepdb1
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 3800
---
apiVersion: v1
kind: Service
metadata:
  name: svc-back
spec:
  type: LoadBalancer
  selector:
    app: my-back
  ports:
  - port: 3800
    targetPort: 3800
