apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-database
  template:
    metadata:
      labels:
        app: my-database
    spec:
      containers:
      - name: my-database
        image: gvenzl/oracle-xe:21.3.0
        env:
        - name: ORACLE_PASSWORD
          value: passwordso1
        - name: APP_USER
          value: APPUSER
        - name: APP_USER_PASSWORD
          value: passwordapp
        resources:
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        ports:
        - containerPort: 1521
---
apiVersion: v1
kind: Service
metadata:
  name: svc-database
spec:
  type: ClusterIP
  selector:
    app: my-database
  ports:
  - port: 1521
    targetPort: 1521
