apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-database
  template:
    metadata:
      labels:
        app: my-database
    spec:
      securityContext:
        runAsUser: 54321    # Oracle User 
        runAsGroup: 54321   # Oinstall group
        fsGroup: 54321      # Oinstall group
      volumes:
        - name: init-script
          configMap:
            name: db-configmap
        - name: oracle-persistent-storage
          persistentVolumeClaim:
            claimName: oracle-pv-claim
      containers:
      - name: my-database
        image: gvenzl/oracle-xe:21.3.0
        env:
        - name: APP_USER
          value: APPUSER
        - name: ORACLE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: oracle-pass
              name: db-secrets
        - name: APP_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: app-user-pass
              name: db-secrets
        resources:
          limits:
            memory: "3Gi"
            cpu: "1500m"
        ports:
        - containerPort: 1521
        volumeMounts:
        - name: init-script
          mountPath: /container-entrypoint-initdb.d
        - name: oracle-persistent-storage
          mountPath: /opt/oracle/oradata
---
apiVersion: v1
kind: Service
metadata:
  name: svc-database
spec:
  type: ClusterIP
  selector:
    app: my-database
  ports:
  - port: 1521
    targetPort: 1521
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  init.sql: |
    -- REMOVE DATA
    -- DELETE FROM PERSON;
    -- DELETE FROM PERSON;
    -- DELETE FROM CATEGORY;

    -- REMOVE TABLE AND SEQUENCE
    -- DROP TABLE CATEGORY;
    -- DROP SEQUENCE SQ_CATEGORY;

    -- REMOVE TABLE AND SEQUENCE
    -- DROP TABLE PERSON;
    -- DROP SEQUENCE SQ_PERSON;

    ALTER SESSION SET CONTAINER=XEPDB1;

    -- PERSON CREATION
    CREATE TABLE APPUSER.PERSON (
      PERSON NUMBER,
      EMAIL VARCHAR2(100) UNIQUE NOT NULL,
      PASSWORD VARCHAR2(1000) NOT NULL,
      PERSON_TOKEN VARCHAR2(1000) NOT NULL,
      FIRST_NAME VARCHAR2(100) NOT NULL,
      LAST_NAME VARCHAR2(100) NOT NULL,
      ADD_DATE DATE DEFAULT SYSDATE,
      MOD_DATE DATE,
      PRIMARY KEY(PERSON)
    );

    -- PERSON SEQUENCE
    CREATE SEQUENCE APPUSER.SQ_PERSON NOCACHE;

    -- CATEGORY CREATION
    CREATE TABLE APPUSER.CATEGORY(
      CATEGORY NUMBER,
      PERSON NUMBER NOT NULL,
      NAME VARCHAR2(100) NOT NULL,
      DESCRIPTION VARCHAR2(200) NOT NULL,
      ADD_DATE DATE DEFAULT SYSDATE,
      MOD_DATE DATE,
      PRIMARY KEY(CATEGORY),
      FOREIGN KEY(PERSON) REFERENCES APPUSER.PERSON(PERSON)
    );

    -- CATEGORY SEQUENCE
    CREATE SEQUENCE APPUSER.SQ_CATEGORY NOCACHE;

    -- CREATE FUNCTION
    CREATE OR REPLACE FUNCTION APPUSER.API_TOKEN(PSECRET VARCHAR2) RETURN VARCHAR2
    IS
        VRESULT VARCHAR2(4000);
    BEGIN
      SELECT UTL_RAW.CAST_TO_VARCHAR2(UTL_I18N.STRING_TO_RAW(STANDARD_HASH(PSECRET, 'MD5'), 'AL32UTF8')) INTO VRESULT from dual;
      RETURN VRESULT;
    END API_TOKEN;
    /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  oracle-pass: cGFzc3dvcmRzbzE=
  app-user-pass: cGFzc3dvcmRhcHA=
