apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-front
  template:
    metadata:
      labels:
        app: my-front
    spec:
      containers:
      - name: my-front
        image: susguzman/so1-s223-front:0.1.3-nginx-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-front
spec:
  type: LoadBalancer
  selector:
    app: my-front
  ports:
  - port: 8888
    targetPort: 80