apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-front
spec:
  selector:
    matchLabels:
      app: my-front
  template:
    metadata:
      labels:
        app: my-front
    spec:
      containers:
      - name: my-front
        image: susguzman/so1-s223-front:0.1.3-nginx-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-front
spec:
  type: LoadBalancer
  selector:
    app: my-front
  ports:
  - port: 8888
    targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-front
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-front
